# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:year/:month/:day/:title/
#relative_permalinks: true

# Setup
title:               공부 기록 블로그
tagline:             '공부 내용 기록하는 블로그'
url:                 https://nobbaggu.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              nobbaggu
  url:               https://nobbaggu.github.io

# Custom vars
version:             1.0.0

plugins:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'

# Tag setting
#collections:
#  tags:
#    output: true
#    permalink: /tags/:path/

#defaults:
#  - scope:
#      path: ''
#      type: tags
#    values:
#      layout: tag

#category_dir: category/
#tag_dir: tag/

nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
#google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
#disqus_short_name: 'wkimdev-gitblog' # leave blank if you don't want disqus