# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:year/:month/:day/:title/
#relative_permalinks: true

# Setup
title:               SW NOMAD의 공부 기록소
tagline:             '자유를 꿈꾸는 소프트웨어 엔지니어'
#description:         예비 프로그래머 노마드입니다.
url:                 https://swnomad.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              SW NOMAD
  url:               https://swnomad.github.io
  #email:             hoisharka@gmail.com

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]

# Tag setting
#collections:
#  tags:
#    output: true
#    permalink: /tags/:path/

#defaults:
#  - scope:
#      path: ''
#      type: tags
#    values:
#      layout: tag


category_dir: category/
tag_dir: tag/

excerpt_separator: ""
