# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:year/:month/:day/:title/
#relative_permalinks: true

# Setup
title:               공부 기록 블로그
tagline:             '취미로 개발하자'
url:                 https://nobbaggu.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              nobbaggu
  url:               https://nobbaggu.github.io

# Custom vars
version:             1.0.0

markdown: kramdown

kramdown:
    input: GFM
    syntax_highlighter: rouge
incremental: true
trace: true

plugins: 
  - jekyll-feed
  - jekyll-paginate

# Tag setting
#collections:
#  tags:
#    output: true
#    permalink: /tags/:path/

#defaults:
#  - scope:
#      path: ''
#      type: tags
#    values:
#      layout: tag

category_dir: category/
tag_dir: tag/

excerpt_separator: ""